// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: legacy.sql

package dbgen

import (
	"context"
)

const hasLegacyHistory = `-- name: HasLegacyHistory :one
SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema=current_schema() AND table_name='sgsp_schema_migrations')
`

func (q *Queries) HasLegacyHistory(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasLegacyHistory)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const legacyChecksum = `-- name: LegacyChecksum :one
SELECT checksum FROM sgsp_schema_migrations WHERE version='001_group_assignments'
`

func (q *Queries) LegacyChecksum(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, legacyChecksum)
	var checksum []byte
	err := row.Scan(&checksum)
	return checksum, err
}
